apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-autoscalling
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: opensearch-cluster-master
  targetCPUUtilizationPercentage: 60